version: '3.3'
services:
    web:
        container_name: web
        restart: always
        depends_on:
            - db
        image: aspendigital/octobercms:latest
        ports:
            - 80:80
        env_file:
            - .env
        volumes:
            - ./plugins:/var/www/html/plugins
            - ./storage/app:/var/www/html/storage/app
            - ./storage/logs:/var/www/html/storage/logs
            - ./themes:/var/www/html/themes

    db:
        image: mariadb
        container_name: db
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: octobercms
            MYSQL_USER: octobercms
            MYSQL_PASSWORD: octobercms
        volumes:
            - $HOME/volumes/mysql/data:/var/lib/mysql
