<?php namespace Hmones\Membership\Components;

class Countries extends \Cms\Classes\ComponentBase
{
    public function componentDetails(){
        return [
            'name' => 'Countries list',
            'description' => 'Retrieves a list of countries with meta data that helps in creating dropdowns for countries in different languages'
        ];
    }

    public function onRun(){
        if($this->page['activeLocale']=="en"){
            $this->page['countries'] = collect([
                ["Afghanistan","af","93"],
                ["Albania","al","355"],
                ["Algeria","dz","213"],
                ["American Samoa","as","1-684"],
                ["Andorra","ad","376"],
                ["Angola","ao","244"],
                ["Anguilla","ai","1-264"],
                ["Antarctica","aq","672"],
                ["Antigua & Barbuda","ag","1-268"],
                ["Argentina","ar","54"],
                ["Armenia","am","374"],
                ["Aruba","aw","297"],
                ["Australia","au","61"],
                ["Austria","at","43"],
                ["Azerbaijan","az","994"],
                ["Bahamas","bs","1-242"],
                ["Bahrain","bh","973"],
                ["Bangladesh","bd","880"],
                ["Barbados","bb","1-246"],
                ["Belarus","by","375"],
                ["Belgium","be","32"],
                ["Belize","bz","501"],
                ["Benin","bj","229"],
                ["Bermuda","bm","1-441"],
                ["Bhutan","bt","975"],
                ["Bolivia","bo","591"],
                ["Caribbean Netherlands","bq","599"],
                ["Bosnia","ba","387"],
                ["Botswana","bw","267"],
                ["Bouvet Island","bv","47"],
                ["Brazil","br","55"],
                ["British Indian Ocean Territory","io","246"],
                ["British Virgin Islands","vg","1-284"],
                ["Brunei","bn","673"],
                ["Bulgaria","bg","359"],
                ["Burkina Faso","bf","226"],
                ["Burundi","bi","257"],
                ["Cape Verde","cv","238"],
                ["Cambodia","kh","855"],
                ["Cameroon","cm","237"],
                ["Canada","ca","1"],
                ["Cayman Islands","ky","1-345"],
                ["Central African Republic","cf","236"],
                ["Chad","td","235"],
                ["Chile","cl","56"],
                ["China","cn","86"],
                ["Hong Kong","hk","852"],
                ["Macau","mo","853"],
                ["Christmas Island","cx","61"],
                ["Cocos (Keeling) Islands","cc","61"],
                ["Colombia","co","57"],
                ["Comoros","km","269"],
                ["Congo - Brazzaville","cg","242"],
                ["Cook Islands","ck","682"],
                ["Costa Rica","cr","506"],
                ["Croatia","hr","385"],
                ["Cuba","cu","53"],
                ["Curaçao","cw","599"],
                ["Cyprus","cy","357"],
                ["Czechia","cz","420"],
                ["Côte d’Ivoire","ci","225"],
                ["North Korea","kp","850"],
                ["Congo - Kinshasa","cd","243"],
                ["Denmark","dk","45"],
                ["Djibouti","dj","253"],
                ["Dominica","dm","1-767"],
                ["Dominican Republic","do","1-809"],
                ["Ecuador","ec","593"],
                ["Egypt","eg","20"],
                ["El Salvador","sv","503"],
                ["Equatorial Guinea","gq","240"],
                ["Eritrea","er","291"],
                ["Estonia","ee","372"],
                ["Ethiopia","et","251"],
                ["Falkland Islands","fk","500"],
                ["Faroe Islands","fo","298"],
                ["Fiji","fj","679"],
                ["Finland","fi","358"],
                ["France","fr","33"],
                ["French Guiana","gf","594"],
                ["French Polynesia","pf","689"],
                ["French Southern Territories","tf","262"],
                ["Gabon","ga","241"],
                ["Gambia","gm","220"],
                ["Georgia","ge","995"],
                ["Germany","de","49"],
                ["Ghana","gh","233"],
                ["Gibraltar","gi","350"],
                ["Greece","gr","30"],
                ["Greenland","gl","299"],
                ["Grenada","gd","1-473"],
                ["Guadeloupe","gp","590"],
                ["Guam","gu","1-671"],
                ["Guatemala","gt","502"],
                ["Guernsey","gg","44"],
                ["Guinea","gn","224"],
                ["Guinea-Bissau","gw","245"],
                ["Guyana","gy","592"],
                ["Haiti","ht","509"],
                ["Heard & McDonald Islands","hm","672"],
                ["Vatican City","va","39-06"],
                ["Honduras","hn","504"],
                ["Hungary","hu","36"],
                ["Iceland","is","354"],
                ["India","in","91"],
                ["Indonesia","id","62"],
                ["Iran","ir","98"],
                ["Iraq","iq","964"],
                ["Ireland","ie","353"],
                ["Isle of Man","im","44"],
                ["Israel","il","972"],
                ["Italy","it","39"],
                ["Jamaica","jm","1-876"],
                ["Japan","jp","81"],
                ["Jersey","je","44"],
                ["Jordan","jo","962"],
                ["Kazakhstan","kz","7"],
                ["Kenya","ke","254"],
                ["Kiribati","ki","686"],
                ["Kuwait","kw","965"],
                ["Kyrgyzstan","kg","996"],
                ["Laos","la","856"],
                ["Latvia","lv","371"],
                ["Lebanon","lb","961"],
                ["Lesotho","ls","266"],
                ["Liberia","lr","231"],
                ["Libya","ly","218"],
                ["Liechtenstein","li","423"],
                ["Lithuania","lt","370"],
                ["Luxembourg","lu","352"],
                ["Madagascar","mg","261"],
                ["Malawi","mw","265"],
                ["Malaysia","my","60"],
                ["Maldives","mv","960"],
                ["Mali","ml","223"],
                ["Malta","mt","356"],
                ["Marshall Islands","mh","692"],
                ["Martinique","mq","596"],
                ["Mauritania","mr","222"],
                ["Mauritius","mu","230"],
                ["Mayotte","yt","262"],
                ["Mexico","mx","52"],
                ["Micronesia","fm","691"],
                ["Monaco","mc","377"],
                ["Mongolia","mn","976"],
                ["Montenegro","me","382"],
                ["Montserrat","ms","1-664"],
                ["Morocco","ma","212"],
                ["Mozambique","mz","258"],
                ["Myanmar","mm","95"],
                ["Namibia","na","264"],
                ["Nauru","nr","674"],
                ["Nepal","np","977"],
                ["Netherlands","nl","31"],
                ["New Caledonia","nc","687"],
                ["New Zealand","nz","64"],
                ["Nicaragua","ni","505"],
                ["Niger","ne","227"],
                ["Nigeria","ng","234"],
                ["Niue","nu","683"],
                ["Norfolk Island","nf","672"],
                ["Northern Mariana Islands","mp","1-670"],
                ["Norway","no","47"],
                ["Oman","om","968"],
                ["Pakistan","pk","92"],
                ["Palau","pw","680"],
                ["Panama","pa","507"],
                ["Papua New Guinea","pg","675"],
                ["Paraguay","py","595"],
                ["Peru","pe","51"],
                ["Philippines","ph","63"],
                ["Pitcairn Islands","pn","870"],
                ["Poland","pl","48"],
                ["Portugal","pt","351"],
                ["Puerto Rico","pr","1"],
                ["Qatar","qa","974"],
                ["South Korea","kr","82"],
                ["Moldova","md","373"],
                ["Romania","ro","40"],
                ["Russia","ru","7"],
                ["Rwanda","rw","250"],
                ["Réunion","re","262"],
                ["St. Barthélemy","bl","590"],
                ["St. Helena","sh","290"],
                ["St. Kitts & Nevis","kn","1-869"],
                ["St. Lucia","lc","1-758"],
                ["St. Martin","mf","590"],
                ["St. Pierre & Miquelon","pm","508"],
                ["St. Vincent & Grenadines","vc","1-784"],
                ["Samoa","ws","685"],
                ["San Marino","sm","378"],
                ["São Tomé & Príncipe","st","239"],
                ["Saudi Arabia","sa","966"],
                ["Senegal","sn","221"],
                ["Serbia","rs","381"],
                ["Seychelles","sc","248"],
                ["Sierra Leone","sl","232"],
                ["Singapore","sg","65"],
                ["Sint Maarten","sx","1-721"],
                ["Slovakia","sk","421"],
                ["Slovenia","si","386"],
                ["Solomon Islands","sb","677"],
                ["Somalia","so","252"],
                ["South Africa","za","27"],
                ["South Georgia & South Sandwich Islands","gs","500"],
                ["South Sudan","ss","211"],
                ["Spain","es","34"],
                ["Sri Lanka","lk","94"],
                ["Palestine","ps","970"],
                ["Sudan","sd","249"],
                ["Suriname","sr","597"],
                ["Svalbard & Jan Mayen","sj","47"],
                ["Swaziland","sz","268"],
                ["Sweden","se","46"],
                ["Switzerland","ch","41"],
                ["Syria","sy","963"],
                ["Tajikistan","tj","992"],
                ["Thailand","th","66"],
                ["Macedonia","mk","389"],
                ["Timor-Leste","tl","670"],
                ["Togo","tg","228"],
                ["Tokelau","tk","690"],
                ["Tonga","to","676"],
                ["Trinidad & Tobago","tt","1-868"],
                ["Tunisia","tn","216"],
                ["Turkey","tr","90"],
                ["Turkmenistan","tm","993"],
                ["Turks & Caicos Islands","tc","1-649"],
                ["Tuvalu","tv","688"],
                ["Uganda","ug","256"],
                ["Ukraine","ua","380"],
                ["United Arab Emirates","ae","971"],
                ["UK","gb","44"],
                ["Tanzania","tz","255"],
                ["U.S. Virgin Islands","vi","1-340"],
                ["US","us","1"],
                ["Uruguay","uy","598"],
                ["Uzbekistan","uz","998"],
                ["Vanuatu","vu","678"],
                ["Venezuela","ve","58"],
                ["Vietnam","vn","84"],
                ["Wallis & Futuna","wf","681"],
                ["Western Sahara","eh","212"],
                ["Yemen","ye","967"],
                ["Zambia","zm","260"],
                ["Zimbabwe","zw","263"],
                ["Åland Islands","ax","358"],
            ]);
        }
        if($this->page['activeLocale']=="ar"){
            $this->page['countries']=collect(
                [
                    ["أفغانستان","af","93"],
                    ["ألبانيا","al","355"],
                    ["الجزائر","dz","213"],
                    ["ساموا الأمريكية","as","1-684"],
                    ["أندورا","ad","376"],
                    ["أنغولا","ao","244"],
                    ["أنغيلا","ai","1-264"],
                    ["أنتاركتيكا","aq","672"],
                    ["أنتيغوا وبربودا","ag","1-268"],
                    ["الأرجنتين","ar","54"],
                    ["أرمينيا","am","374"],
                    ["أروبا","aw","297"],
                    ["أستراليا","au","61"],
                    ["النمسا","at","43"],
                    ["أذربيجان","az","994"],
                    ["جزر البهاما","bs","1-242"],
                    ["البحرين","bh","973"],
                    ["بنغلاديش","bd","880"],
                    ["بربادوس","bb","1-246"],
                    ["بيلاروس","by","375"],
                    ["بلجيكا","be","32"],
                    ["بليز","bz","501"],
                    ["بنن","bj","229"],
                    ["برمودا","bm","1-441"],
                    ["بوتان","bt","975"],
                    ["بوليفيا (دولة - المتعددة القوميات)","bo","591"],
                    ["بونير وسان يوستاتيوس وسابا","bq","599"],
                    ["البوسنة والهرسك","ba","387"],
                    ["بوتسوانا","bw","267"],
                    ["جزيرة بوفيت","bv","47"],
                    ["البرازيل","br","55"],
                    ["المحيط الهندي الإقليم البريطاني في","io","246"],
                    ["جزر فرجن البريطانية","vg","1-284"],
                    ["بروني دار السلام","bn","673"],
                    ["بلغاريا","bg","359"],
                    ["بوركينا فاسو","bf","226"],
                    ["بوروندي","bi","257"],
                    ["كابو فيردي","cv","238"],
                    ["كمبوديا","kh","855"],
                    ["الكاميرون","cm","237"],
                    ["كندا","ca","1"],
                    ["جزر كايمان","ky","1-345"],
                    ["جمهورية أفريقيا الوسطى","cf","236"],
                    ["تشاد","td","235"],
                    ["شيلي","cl","56"],
                    ["الصين","cn","86"],
                    ["منطقة هونغ كونغ الصينية الإدارية الخاصة","hk","852"],
                    ["منطقة ماكاو الإدارية الخاصة التابعة للصين","mo","853"],
                    ["جزيرة كريسماس","cx","61"],
                    ["جزر كوكوس (كيلينغ)","cc","61"],
                    ["كولومبيا","co","57"],
                    ["جزر القمر","km","269"],
                    ["الكونغو","cg","242"],
                    ["جزر كوك","ck","682"],
                    ["كوستاريكا","cr","506"],
                    ["كرواتيا","hr","385"],
                    ["كوبا","cu","53"],
                    ["كوراساو","cw","599"],
                    ["قبرص","cy","357"],
                    ["تشيكيا","cz","420"],
                    ["كوت ديفوار","ci","225"],
                    ["جمهورية كوريا الشعبية الديمقراطية","kp","850"],
                    ["جمهورية الكونغو الديمقراطية","cd","243"],
                    ["الدانمرك","dk","45"],
                    ["جيبوتي","dj","253"],
                    ["دومينيكا","dm","1-767"],
                    ["الجمهورية الدومينيكية","do","1-809"],
                    ["إكوادور","ec","593"],
                    ["مصر","eg","20"],
                    ["السلفادور","sv","503"],
                    ["غينيا الاستوائية","gq","240"],
                    ["إريتريا","er","291"],
                    ["إستونيا","ee","372"],
                    ["إثيوبيا","et","251"],
                    ["جزر فوكلاند (مالفيناس)","fk","500"],
                    ["جزر فايرو","fo","298"],
                    ["فيجي","fj","679"],
                    ["فنلندا","fi","358"],
                    ["فرنسا","fr","33"],
                    ["غيانا الفرنسية","gf","594"],
                    ["بولينيزيا الفرنسية","pf","689"],
                    ["الأراضي الفرنسية الجنوبية الجنوبية","tf","262"],
                    ["غابون","ga","241"],
                    ["غامبيا","gm","220"],
                    ["جورجيا","ge","995"],
                    ["ألمانيا","de","49"],
                    ["غانا","gh","233"],
                    ["جبل طارق","gi","350"],
                    ["اليونان","gr","30"],
                    ["غرينلند","gl","299"],
                    ["غرينادا","gd","1-473"],
                    ["غواديلوب","gp","590"],
                    ["غوام","gu","1-671"],
                    ["غواتيمالا","gt","502"],
                    ["غيرنزي","gg","44"],
                    ["غينيا","gn","224"],
                    ["غينيا - بيساو","gw","245"],
                    ["غيانا","gy","592"],
                    ["هايتي","ht","509"],
                    ["جزيرة هيرد وجزر ماكدونالد","hm","672"],
                    ["الكرسي الرسولي","va","39-06"],
                    ["هندوراس","hn","504"],
                    ["هنغاريا","hu","36"],
                    ["آيسلندا","is","354"],
                    ["الهند","in","91"],
                    ["إندونيسيا","id","62"],
                    ["إيران (جمهورية - الإسلامية)","ir","98"],
                    ["العراق","iq","964"],
                    ["آيرلندا","ie","353"],
                    ["جزيرة مان","im","44"],
                    ["إسرائيل","il","972"],
                    ["إيطاليا","it","39"],
                    ["جامايكا","jm","1-876"],
                    ["اليابان","jp","81"],
                    ["جيرزي","je","44"],
                    ["الأردن","jo","962"],
                    ["كازاخستان","kz","7"],
                    ["كينيا","ke","254"],
                    ["كيريباس","ki","686"],
                    ["الكويت","kw","965"],
                    ["قيرغيزستان","kg","996"],
                    ["جمهورية لاو الديمقراطية الشعبية","la","856"],
                    ["لاتفيا","lv","371"],
                    ["لبنان","lb","961"],
                    ["ليسوتو","ls","266"],
                    ["ليبريا","lr","231"],
                    ["ليبيا","ly","218"],
                    ["ليختنشتاين","li","423"],
                    ["ليتوانيا","lt","370"],
                    ["لكسمبرغ","lu","352"],
                    ["مدغشقر","mg","261"],
                    ["ملاوي","mw","265"],
                    ["ماليزيا","my","60"],
                    ["ملديف","mv","960"],
                    ["مالي","ml","223"],
                    ["مالطة","mt","356"],
                    ["جزر مارشال","mh","692"],
                    ["مارتينيك","mq","596"],
                    ["موريتانيا","mr","222"],
                    ["موريشيوس","mu","230"],
                    ["جزيرة مايوت","yt","262"],
                    ["المكسيك","mx","52"],
                    ["ميكرونيزيا (ولايات - الموحدة)","fm","691"],
                    ["موناكو","mc","377"],
                    ["منغوليا","mn","976"],
                    ["الجبل الأسود","me","382"],
                    ["مونتسيرات","ms","1-664"],
                    ["المغرب","ma","212"],
                    ["موزامبيق","mz","258"],
                    ["ميانمار","mm","95"],
                    ["ناميبيا","na","264"],
                    ["ناورو","nr","674"],
                    ["نيبال","np","977"],
                    ["هولندا","nl","31"],
                    ["كاليدونيا الجديدة","nc","687"],
                    ["نيوزيلندا","nz","64"],
                    ["نيكاراغوا","ni","505"],
                    ["النيجر","ne","227"],
                    ["نيجيريا","ng","234"],
                    ["نيوي","nu","683"],
                    ["جزيرة نورفلك","nf","672"],
                    ["جزر ماريانا الشمالية","mp","1-670"],
                    ["النرويج","no","47"],
                    ["عمان","om","968"],
                    ["باكستان","pk","92"],
                    ["بالاو","pw","680"],
                    ["بنما","pa","507"],
                    ["بابوا غينيا الجديدة","pg","675"],
                    ["باراغواي","py","595"],
                    ["بيرو","pe","51"],
                    ["الفلبين","ph","63"],
                    ["بيتكيرن","pn","870"],
                    ["بولندا","pl","48"],
                    ["البرتغال","pt","351"],
                    ["بورتوريكو","pr","1"],
                    ["قطر","qa","974"],
                    ["جمهورية كوريا","kr","82"],
                    ["جمهورية مولدوفا","md","373"],
                    ["رومانيا","ro","40"],
                    ["الاتحاد الروسي","ru","7"],
                    ["رواندا","rw","250"],
                    ["ريونيون","re","262"],
                    ["سان بارتليمي","bl","590"],
                    ["سانت هيلانة","sh","290"],
                    ["سانت كيتس ونيفس","kn","1-869"],
                    ["سانت لوسيا","lc","1-758"],
                    ["سا�� مارتن","mf","590"],
                    ["سان بيار وميكلون","pm","508"],
                    ["سانت فنسنت وجزر غرينادين","vc","1-784"],
                    ["ساموا","ws","685"],
                    ["سان مارينو","sm","378"],
                    ["سان تومي وبرينسيبي","st","239"],
                    ["المملكة العربية السعودية","sa","966"],
                    ["السنغال","sn","221"],
                    ["صربيا","rs","381"],
                    ["سيشيل","sc","248"],
                    ["سيراليون","sl","232"],
                    ["سنغافورة","sg","65"],
                    ["سانت مارتن","sx","1-721"],
                    ["سلوفاكيا","sk","421"],
                    ["سلوفينيا","si","386"],
                    ["جزر سليمان","sb","677"],
                    ["الصومال","so","252"],
                    ["جنوب أفريقيا","za","27"],
                    ["جورجيا الجنوبية وجزر ساندويتش الجنوبية","gs","500"],
                    ["جنوب السودان","ss","211"],
                    ["إسبانيا","es","34"],
                    ["سري لانكا","lk","94"],
                    ["دولة فلسطين","ps","970"],
                    ["السودان","sd","249"],
                    ["سورينام","sr","597"],
                    ["جزر سفالبارد وجان ماين","sj","47"],
                    ["سوازيلند","sz","268"],
                    ["السويد","se","46"],
                    ["سويسرا","ch","41"],
                    ["الجمهورية العربية السورية","sy","963"],
                    ["طاجيكستان","tj","992"],
                    ["تايلند","th","66"],
                    ["جمهورية مقدونيا اليوغوسلافية سابقاً","mk","389"],
                    ["تيمور- ليشتي","tl","670"],
                    ["توغو","tg","228"],
                    ["توكيلاو","tk","690"],
                    ["تونغا","to","676"],
                    ["ترينيداد وتوباغو","tt","1-868"],
                    ["تونس","tn","216"],
                    ["تركيا","tr","90"],
                    ["تركمانستان","tm","993"],
                    ["جزر تركس وكايكوس","tc","1-649"],
                    ["توفالو","tv","688"],
                    ["أوغندا","ug","256"],
                    ["أوكرانيا","ua","380"],
                    ["الإمارات العربية المتحدة","ae","971"],
                    ["المملكة المتحدة لبريطانيا العظمى وآيرلندا الشمالية","gb","44"],
                    ["جمهورية تنزانيا المتحدة","tz","255"],
                    ["جزر فرجن التابعة للولايات المتحدة","vi","1-340"],
                    ["الولايات المتحدة الأمريكية","us","1"],
                    ["أوروغواي","uy","598"],
                    ["أوزبكستان","uz","998"],
                    ["فانواتو","vu","678"],
                    ["فنزويلا (جمهورية - البوليفارية)","ve","58"],
                    ["فييت نام","vn","84"],
                    ["جزر واليس وفوتونا","wf","681"],
                    ["الصحراء الغربية","eh","212"],
                    ["اليمن","ye","967"],
                    ["زامبيا","zm","260"],
                    ["زمبابوي","zw","263"],
                    ["جزر ألاند","ax","358"],
                ]
            );
        }
        if($this->page['activeLocale']=="fr"){
            $this->page['countries']=collect(
                [
                    ["Afghanistan","af","93"],
                    ["Albanie","al","355"],
                    ["Algérie","dz","213"],
                    ["Samoa américaines","as","1-684"],
                    ["Andorre","ad","376"],
                    ["Angola","ao","244"],
                    ["Anguilla","ai","1-264"],
                    ["Antarctique","aq","672"],
                    ["Antigua-et-Barbuda","ag","1-268"],
                    ["Argentine","ar","54"],
                    ["Arménie","am","374"],
                    ["Aruba","aw","297"],
                    ["Australie","au","61"],
                    ["Autriche","at","43"],
                    ["Azerbaïdjan","az","994"],
                    ["Bahamas","bs","1-242"],
                    ["Bahreïn","bh","973"],
                    ["Bangladesh","bd","880"],
                    ["Barbade","bb","1-246"],
                    ["Bélarus","by","375"],
                    ["Belgique","be","32"],
                    ["Belize","bz","501"],
                    ["Bénin","bj","229"],
                    ["Bermudes","bm","1-441"],
                    ["Bhoutan","bt","975"],
                    ["Bolivie (État plurinational de)","bo","591"],
                    ["Bonaire Saint-Eustache et Saba","bq","599"],
                    ["Bosnie-Herzégovine","ba","387"],
                    ["Botswana","bw","267"],
                    ["Île Bouvet","bv","47"],
                    ["Brésil","br","55"],
                    ["Territoire britannique de l'océan Indien","io","246"],
                    ["Îles Vierges britanniques","vg","1-284"],
                    ["Brunéi Darussalam","bn","673"],
                    ["Bulgarie","bg","359"],
                    ["Burkina Faso","bf","226"],
                    ["Burundi","bi","257"],
                    ["Cabo Verde","cv","238"],
                    ["Cambodge","kh","855"],
                    ["Cameroun","cm","237"],
                    ["Canada","ca","1"],
                    ["Îles Caïmanes","ky","1-345"],
                    ["République centrafricaine","cf","236"],
                    ["Tchad","td","235"],
                    ["Chili","cl","56"],
                    ["Chine","cn","86"],
                    ["Hong Kong","hk","852"],
                    ["Macao","mo","853"],
                    ["Île Christmas","cx","61"],
                    ["Îles des Cocos (Keeling)","cc","61"],
                    ["Colombie","co","57"],
                    ["Comores","km","269"],
                    ["Congo","cg","242"],
                    ["Îles Cook","ck","682"],
                    ["Costa Rica","cr","506"],
                    ["Croatie","hr","385"],
                    ["Cuba","cu","53"],
                    ["Curaçao","cw","599"],
                    ["Chypre","cy","357"],
                    ["Tchéquie","cz","420"],
                    ["Côte d'Ivoire","ci","225"],
                    ["République populaire démocratique de Corée","kp","850"],
                    ["République démocratique du Congo","cd","243"],
                    ["Danemark","dk","45"],
                    ["Djibouti","dj","253"],
                    ["Dominique","dm","1-767"],
                    ["République dominicaine","do","1-809"],
                    ["Équateur","ec","593"],
                    ["Égypte","eg","20"],
                    ["El Salvador","sv","503"],
                    ["Guinée équatoriale","gq","240"],
                    ["Érythrée","er","291"],
                    ["Estonie","ee","372"],
                    ["Éthiopie","et","251"],
                    ["Îles Falkland (Malvinas)","fk","500"],
                    ["Îles Féroé","fo","298"],
                    ["Fidji","fj","679"],
                    ["Finlande","fi","358"],
                    ["France","fr","33"],
                    ["Guyane française","gf","594"],
                    ["Polynésie française","pf","689"],
                    ["Terres australes françaises","tf","262"],
                    ["Gabon","ga","241"],
                    ["Gambie","gm","220"],
                    ["Géorgie","ge","995"],
                    ["Allemagne","de","49"],
                    ["Ghana","gh","233"],
                    ["Gibraltar","gi","350"],
                    ["Grèce","gr","30"],
                    ["Groenland","gl","299"],
                    ["Grenade","gd","1-473"],
                    ["Guadeloupe","gp","590"],
                    ["Guam","gu","1-671"],
                    ["Guatemala","gt","502"],
                    ["Guernesey","gg","44"],
                    ["Guinée","gn","224"],
                    ["Guinée-Bissau","gw","245"],
                    ["Guyana","gy","592"],
                    ["Haïti","ht","509"],
                    ["Île Heard-et-Îles MacDonald","hm","672"],
                    ["Saint-Siège","va","39-06"],
                    ["Honduras","hn","504"],
                    ["Hongrie","hu","36"],
                    ["Islande","is","354"],
                    ["Inde","in","91"],
                    ["Indonésie","id","62"],
                    ["Iran (République islamique d')","ir","98"],
                    ["Iraq","iq","964"],
                    ["Irlande","ie","353"],
                    ["Île de Man","im","44"],
                    ["Israël","il","972"],
                    ["Italie","it","39"],
                    ["Jamaïque","jm","1-876"],
                    ["Japon","jp","81"],
                    ["Jersey","je","44"],
                    ["Jordanie","jo","962"],
                    ["Kazakhstan","kz","7"],
                    ["Kenya","ke","254"],
                    ["Kiribati","ki","686"],
                    ["Koweït","kw","965"],
                    ["Kirghizistan","kg","996"],
                    ["République démocratique populaire lao","la","856"],
                    ["Lettonie","lv","371"],
                    ["Liban","lb","961"],
                    ["Lesotho","ls","266"],
                    ["Libéria","lr","231"],
                    ["Libye","ly","218"],
                    ["Liechtenstein","li","423"],
                    ["Lituanie","lt","370"],
                    ["Luxembourg","lu","352"],
                    ["Madagascar","mg","261"],
                    ["Malawi","mw","265"],
                    ["Malaisie","my","60"],
                    ["Maldives","mv","960"],
                    ["Mali","ml","223"],
                    ["Malte","mt","356"],
                    ["Îles Marshall","mh","692"],
                    ["Martinique","mq","596"],
                    ["Mauritanie","mr","222"],
                    ["Maurice","mu","230"],
                    ["Mayotte","yt","262"],
                    ["Mexique","mx","52"],
                    ["Micronésie (États fédérés de)","fm","691"],
                    ["Monaco","mc","377"],
                    ["Mongolie","mn","976"],
                    ["Monténégro","me","382"],
                    ["Montserrat","ms","1-664"],
                    ["Maroc","ma","212"],
                    ["Mozambique","mz","258"],
                    ["Myanmar","mm","95"],
                    ["Namibie","na","264"],
                    ["Nauru","nr","674"],
                    ["Népal","np","977"],
                    ["Pays-Bas","nl","31"],
                    ["Nouvelle-Calédonie","nc","687"],
                    ["Nouvelle-Zélande","nz","64"],
                    ["Nicaragua","ni","505"],
                    ["Niger","ne","227"],
                    ["Nigéria","ng","234"],
                    ["Nioué","nu","683"],
                    ["Île Norfolk","nf","672"],
                    ["Îles Mariannes du Nord","mp","1-670"],
                    ["Norvège","no","47"],
                    ["Oman","om","968"],
                    ["Pakistan","pk","92"],
                    ["Palaos","pw","680"],
                    ["Panama","pa","507"],
                    ["Papouasie-Nouvelle-Guinée","pg","675"],
                    ["Paraguay","py","595"],
                    ["Pérou","pe","51"],
                    ["Philippines","ph","63"],
                    ["Pitcairn","pn","870"],
                    ["Pologne","pl","48"],
                    ["Portugal","pt","351"],
                    ["Porto Rico","pr","1"],
                    ["Qatar","qa","974"],
                    ["République de Corée","kr","82"],
                    ["République de Moldova","md","373"],
                    ["Roumanie","ro","40"],
                    ["Fédération de Russie","ru","7"],
                    ["Rwanda","rw","250"],
                    ["Réunion","re","262"],
                    ["Saint-Barthélemy","bl","590"],
                    ["Sainte-Hélène","sh","290"],
                    ["Saint-Kitts-et-Nevis","kn","1-869"],
                    ["Sainte-Lucie","lc","1-758"],
                    ["Saint-Martin (partie française)","mf","590"],
                    ["Saint-Pierre-et-Miquelon","pm","508"],
                    ["Saint-Vincent-et-les Grenadines","vc","1-784"],
                    ["Samoa","ws","685"],
                    ["Saint-Marin","sm","378"],
                    ["Sao Tomé-et-Principe","st","239"],
                    ["Arabie saoudite","sa","966"],
                    ["Sénégal","sn","221"],
                    ["Serbie","rs","381"],
                    ["Seychelles","sc","248"],
                    ["Sierra Leone","sl","232"],
                    ["Singapour","sg","65"],
                    ["Saint-Martin (partie néerlandaise)","sx","1-721"],
                    ["Slovaquie","sk","421"],
                    ["Slovénie","si","386"],
                    ["Îles Salomon","sb","677"],
                    ["Somalie","so","252"],
                    ["Afrique du Sud","za","27"],
                    ["Géorgie du Sud-et-les Îles Sandwich du Sud","gs","500"],
                    ["Soudan du Sud","ss","211"],
                    ["Espagne","es","34"],
                    ["Sri Lanka","lk","94"],
                    ["État de Palestine","ps","970"],
                    ["Soudan","sd","249"],
                    ["Suriname","sr","597"],
                    ["Îles Svalbard-et-Jan Mayen","sj","47"],
                    ["Swaziland","sz","268"],
                    ["Suède","se","46"],
                    ["Suisse","ch","41"],
                    ["République arabe syrienne","sy","963"],
                    ["Tadjikistan","tj","992"],
                    ["Thaïlande","th","66"],
                    ["ex-République yougoslave de Macédoine","mk","389"],
                    ["Timor-Leste","tl","670"],
                    ["Togo","tg","228"],
                    ["Tokélaou","tk","690"],
                    ["Tonga","to","676"],
                    ["Trinité-et-Tobago","tt","1-868"],
                    ["Tunisie","tn","216"],
                    ["Turquie","tr","90"],
                    ["Turkménistan","tm","993"],
                    ["Îles Turques-et-Caïques","tc","1-649"],
                    ["Tuvalu","tv","688"],
                    ["Ouganda","ug","256"],
                    ["Ukraine","ua","380"],
                    ["Émirats arabes unis","ae","971"],
                    ["Royaume-Uni de Grande-Bretagne et d'Irlande du Nord","gb","44"],
                    ["République-Unie de Tanzanie","tz","255"],
                    ["Îles Vierges américaines","vi","1-340"],
                    ["États-Unis d'Amérique","us","1"],
                    ["Uruguay","uy","598"],
                    ["Ouzbékistan","uz","998"],
                    ["Vanuatu","vu","678"],
                    ["Venezuela (République bolivarienne du)","ve","58"],
                    ["Viet Nam","vn","84"],
                    ["Îles Wallis-et-Futuna","wf","681"],
                    ["Sahara occidental","eh","212"],
                    ["Yémen","ye","967"],
                    ["Zambie","zm","260"],
                    ["Zimbabwe","zw","263"],
                    ["Îles d'Åland","ax","358"],

                ]
            );
        }
    }
}

?>